//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParkDatabase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartParkDatabase.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SET FOREIGN_KEY_CHECKS=0;
        ///
        ///-- ----------------------------
        ///-- Table structure for sps_manager_login
        ///-- ----------------------------
        ///DROP TABLE IF EXISTS `sps_manager_login`;
        ///CREATE TABLE `sps_manager_login` (
        ///  `id` int(11) NOT NULL AUTO_INCREMENT,
        ///  `login_time` datetime NOT NULL COMMENT &apos;门卫登录时间&apos;,
        ///  `logout_time` datetime DEFAULT NULL COMMENT &apos;门卫登出时间&apos;,
        ///  `manager_id` int(11) NOT NULL COMMENT &apos;门卫ID&apos;,
        ///  PRIMARY KEY (`id`),
        ///  KEY `FK_LOGIN_MANAGER_idx` (`manager_id`),
        ///  CONSTRAINT `FK_LOGIN_MANAG [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitSql {
            get {
                return ResourceManager.GetString("InitSql", resourceCulture);
            }
        }
    }
}
